apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-shipping
  namespace: backends
  labels:
    app: backend-shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-shipping
  template:
    metadata:
      labels:
        app: backend-shipping
    spec:
      containers:
      - name: backend-shipping
        image: chaphe/backend-shipping-image:1.0
        ports: 
        - containerPort: 3000
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq-service
---
apiVersion: v1
kind: Service
metadata:
  name: backend-shipping
  namespace: backends
spec:
  type: NodePort
  selector:
    app: backend-shipping
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000