apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-catalog
  namespace: backends
  labels:
    app: backend-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-catalog
  template:
    metadata:
      labels:
        app: backend-catalog
    spec:
      containers:
      - name: backend-catalog
        image: chaphe/backend-catalog-image:1.0
        ports: 
        - containerPort: 8081
        env:
        - name: MYSQL_DB_HOST
          value: mysql-service.databases.svc.cluster.local
        - name: MYSQL_DB_PORT
          value: '3306'
        - name: MYSQL_DB_USERNAME
          value: root
        - name: MYSQL_DB_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-catalog
  namespace: backends
spec:
  type: NodePort
  selector:
    app: backend-catalog
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081