apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-reviews
  namespace: backends
  labels:
    app: backend-reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-reviews
  template:
    metadata:
      labels:
        app: backend-reviews
    spec:
      containers:
      - name: backend-reviews
        image: chaphe/backend-reviews-image:1.0
        ports: 
        - containerPort: 3000
        env:
        - name: MONGODB_HOST
          value: mongo-service.databases.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: backend-reviews
  namespace: backends
spec:
  type: NodePort
  selector:
    app: backend-reviews
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000