apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-catalog
  namespace: databases
  labels:
    app: database-catalog-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-catalog-mysql
  template:
    metadata:
      labels:
        app: database-catalog-mysql
    spec:
      containers:
      - name: mysqldb
        image: mysql
        ports: 
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: catalog-library
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: databases
spec:
  type: ClusterIP
  selector:
    app: database-catalog-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-external-service
  namespace: databases
spec:
  type: NodePort
  selector:
    app: database-catalog-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306