apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-reviews
  namespace: databases
  labels:
    app: database-reviews-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-reviews-mongo
  template:
    metadata:
      labels:
        app: database-reviews-mongo
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports: 
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: test
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: databases
spec:
  type: ClusterIP
  selector:
    app: database-reviews-mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-external-service
  namespace: databases
spec:
  type: NodePort
  selector:
    app: database-reviews-mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017