apiVersion: apps/v1
kind: Deployment
metadata:
  name: fronted-reviews
  namespace: fronteds
  labels:
    app: fronted-reviews
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: fronted-reviews
  template:
    metadata:
      labels:
        app: fronted-reviews
    spec:
      containers: 
      - name: fronted-reviews-container
        image: chaphe/frontend-reviews-image:1.0
        ports:
        - containerPort: 80
        env:
        - name: REVIEWS_URL
          value: http://localhost:31061
---
apiVersion: v1
kind: Service
metadata:
  name: fronted-reviews-service
  namespace: fronteds
spec:
  type: NodePort
  selector:
    app: fronted-reviews
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
