apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmqcluster
  namespace: backends
  labels:
    app: rabbitmqcluster

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmqcluster
  template:
    metadata:
      labels:
        app: rabbitmqcluster
    spec:
      containers:
      - name: rabbitmqcluster
        image: rabbitmq:3-management
        ports: 
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: backends
spec:
  type: ClusterIP
  selector:
    app: rabbitmqcluster
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-external-service
  namespace: backends
spec:
  type: NodePort
  selector:
    app: rabbitmqcluster
  ports:
  - protocol: TCP
    port: 15672
    targetPort: 15672